{% set name = "us" %}
{% set version = "3.1.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "e347963e8d24a1ca7437af443fa68591776847b50c8650d8ef0eb53482e705c2" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}
  patches:
    - patches/0001-loosen-jellyfish-ties.patch

build:
  # no jellyfish>=0.11.2 on s390x
  skip: True  # [py<36 or s390x]
  entry_points:
    - states = us.cli.states:main
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - jellyfish >=0.11.2

test:
  source_files:
    - us/tests
  imports:
    - us
    - us.cli
  requires:
    - pip
    - pytest
    - pytz
  commands:
    - states --help
    - pip check
    - pytest -v us/tests

about:
  home: https://github.com/unitedstates/python-us
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: US state meta information and other fun stuff
  description: |
    A package for easily working with US and state metadata.
  dev_url: https://github.com/unitedstates/python-us
  doc_url: https://pypi.org/project/us/

extra:
  recipe-maintainers:
    - pmlandwehr
    - dorisjlee
