{% set name = "us" %}
{% set version = "1.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "09dc9ba763e2e4399e6a042104f3e415a7de6bfa4df6f557b4f19e3ba9a22fda" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - states = us.cli.states:main
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jellyfish ==0.5.1
    - setuptools

test:
  imports:
    - us
    - us.cli

  commands:
    - states --help

about:
  home: https://github.com/unitedstates/python-us
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'US state meta information and other fun stuff'
  dev_url: https://github.com/unitedstates/python-us

extra:
  recipe-maintainers:
    - pmlandwehr
