travis:
  secure:
    BINSTAR_TOKEN: FI2GXbKdObxvyO4igIi/ZcNJTUFp9PrBZBnbUgDtxrUvSCKA23fON+wJKBLqn7Qs2Wgmpx4XOPSGwM7AKXaL4n6KCai/MlB69jayZhMGrWnCaIZQNcUASiqi5julMl8x822MExMyn3hfEAInWJsdltzVhetmiVd6Gi1bG0qTvGz3iSlc9NsGf9R7BKaaDkZ7FrCepODVTrE8DYwsvoNDtVk4Zn3dLMEHLW+Ym6XTBkIyOGjiJ4h1aQPmDcwFecgftMgVR+nH4RAsd2eDb8yJu/s8RLb4hgAgkExiikYhk8cdL2Z62bgA21RpgT2C2a+VqHjduNCsA5Kk6j27kOcOGawbPln3iFMSVGsjM0bRlkdQzvP1tNeCUMFgnlDZvxk0EMqi3BiLfWyta/pEkCGoYQYNyRPs5QLR6cDN+CwqNPdnP+YIlEQKGFQ0lcmO2KOo1k6u8L4XOh5K9xkZLY7+hGjgpdrWp3KIyaytvp04sh070DfWixAaeVWABkX3BQYsK4aKk6+6VJ1BSLbaBTteEVUiCJ+QjMtj9St/hxTyrG9/v2XOYw4BtUOpTWwVtOvlK/MLMSSd+NZsBHJMk4sKdfbP1rZgS61UDQezDv6IX9wuySXIUjNE2kDY0ZBGLqm/kx8gGWAqzY52giICyUqYcm383ebKKsSJArI2kPeGviQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
