travis:
  secure:
    BINSTAR_TOKEN: pKhyrATfiy2H/i1ZWy4y1wia9hKXH+Aw1m379fCiv8FEBTtHVW4rnQ2nO8EbPv+i8Ei/uyK5bUlhgrdI6rogBBDwbDC73GjGII3fHwVxBmJZVtsGwlhfmpuQlzPm7zy7HFr1l6ihXh4rFR7qWauCe/5AyYJwK7XFs1La+cBxpmg/UaUlEb7FzfGXOJnBiqXQhEtC6/nCWjJbK85fCZqs5nlRGnVGKRXs1eQM4SL+y+djIWNXUPIP5g9C47ZiBjwpTfQ/RYO7zLSVjCJ3SXuo4wi129JNAKSFS9blI8Qz/CG+xIcNQUJnvt2QSGNSIQN+87WmIztMsebEiizaHwNpd+bARyW6eHJdhfS9DU97u2HTWzeH3+6L2XWOEjBREpBy1uH2hMs4/S9zxGsJJWvheP96h0I1btAKzXVHmK/g5CAiH/epSfYIVSmuZrGmWOGytQgtktm2cYnI/d/I3gv9eCEDUHg9aGgQPmgWiE/pKLf+7zUS2nVhMGgCR8++z+WJTkBOEBvTDM5hpm/L1fbWsM6pB/k5pBfheA6+T2xPraixb1U2CdPtcfJty5OPpmWbrb1B8vu7ndTUzsTkaa8Ta8cGPXZXOo4wQzVdzBEG2XkSkECQXHMOS4CZqiU4ifaJcyxoMhiuigxr+iE1Wp+PST2htA6rrJOThAc2qdBLScg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
